### ISSUE TITLE
Do you see a problem with not ignore *.test-d.ts files and instead

### ISSUE THREAD

**Issue by gg-oura** [zposten/jest-tsd#9]
I like seeing the errors in my ide which requires that tsconfig have scope including. 

this means that i cannot use `expectError` but do you see a problem with doing the following instead so that the test is still valid

```
expectAssignable<any>(
// @ts-expect-error reason here
myType
); 
```

**Comment by 0livare** [comment]
Excluding `.test-d.ts` files in your tsconfig file should not prevent the errors from showing up in your IDE when you have the file open. But what it will do is prevent these test files from being included in your app's compiled output, which is a very good thing.

I would definitely recommend having this in your tsconfig file:

```json
"exclude": ["**/*.test-d.ts", "**/*.test-d.tsx"],
```

However, if for whatever reason that doesn't work for you and using `@ts-expect-error` does, than by all means do it that way. I have a hunch that it won't work exactly in the way you're expecting though because `@ts-expect-error` will not report errors in the same way that `expectError()` does.
